apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

# Override replica counts for production
patches:
  - target:
      kind: Deployment
      name: vcm-backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Deployment
      name: vcm-frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Ingress
      name: vcm-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: vcm.vcm.DavoudTeimouri.ir
      - op: replace
        path: /spec/tls/0/hosts/0
        value: vcm.vcm.DavoudTeimouri.ir

images:
  - name: ghcr.io/DavoudTeimouri/vsphere-compliance-manager/backend
    newTag: "1.0.0"
  - name: ghcr.io/DavoudTeimouri/vsphere-compliance-manager/frontend
    newTag: "1.0.0"
