apiVersion: v2
name: vsphere-compliance-manager
description: Enterprise VMware vCenter DRS & Storage Compliance Platform
type: application
version: 1.3.6-beta
appVersion: 1.3.6-beta
home: https://github.com/davoudteimouri/vsphere-compliance-manager
sources:
  - https://github.com/davoudteimouri/vsphere-compliance-manager
maintainers:
  - name: Davoud Teimouri
keywords:
  - vmware
  - vcenter
  - compliance
  - drs
  - monitoring
