apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vcm

resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - redis.yaml
  - volumes/pvc-uploads.yaml
  - backend.yaml
  - frontend.yaml

commonLabels:
  app.kubernetes.io/name: vsphere-compliance-manager
  app.kubernetes.io/managed-by: kustomize
