apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vcm

resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - backend.yaml
  - frontend.yaml

commonLabels:
  app.kubernetes.io/name: vsphere-compliance-manager
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/managed-by: kustomize
