apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

images:
  - name: ghcr.io/davoudteimouri/vsphere-compliance-manager/backend
    newTag: "1.3.3-beta"
  - name: ghcr.io/davoudteimouri/vsphere-compliance-manager/frontend
    newTag: "1.3.3-beta"

# Dev: single replica, reduced resources
patches:
  - target:
      kind: Deployment
      name: vcm-backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: vcm-frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Ingress
      name: vcm-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: vcm.dev.local
