apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: vcm-backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/env/-
        value:
          name: LOG_LEVEL
          value: DEBUG
      - op: replace
        path: /spec/template/spec/containers/0/env/-
        value:
          name: APP_ENV
          value: development
  - target:
      kind: Deployment
      name: vcm-frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Ingress
      name: vcm-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: vcm-dev.example.com

images:
  - name: ghcr.io/davoudteimouri/vsphere-compliance-manager/backend
    newTag: "1.3.4-beta"
  - name: ghcr.io/davoudteimouri/vsphere-compliance-manager/frontend
    newTag: "1.3.4-beta"
